[build]
builder = "nixpacks"
buildCommand = "npm run build:prod"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
releaseCommand = "npx prisma migrate deploy"
