import type { AnimationPackage } from "../../registry/packages";
import {
  atmosphereBarsFactory,
  atmosphereColorWashFactory,
  atmosphereGlowFactory,
  atmosphereRadialFactory,
  atmosphereVignetteFactory,
  atmosphereKaleidoscopeFactory,
  atmosphereSonarFactory,
  atmosphereGlitchFactory,
  atmosphereShatterFactory,
  atmosphereLaserGridFactory,
  atmosphereGlyphRainFactory,
  atmosphereFireflyFactory,
  atmosphereWarpStarfieldFactory,
} from "./AtmosphereFxScenes";
import { atmosphereFxManifest } from "./manifest";

/**
 * Atmosphere FX package registers animations only — no ScenePresetDef entries,
 * so presets never enter the theatre rotation bag.
 */
export const atmosphereFxPackage: AnimationPackage = {
  manifest: atmosphereFxManifest,
  animations: [
    {
      id: "atmosphereGlow",
      label: "Atmosphere Glow",
      factory: atmosphereGlowFactory,
      visualType: "canvas",
      mood: "calm",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereVignette",
      label: "Atmosphere Vignette",
      factory: atmosphereVignetteFactory,
      visualType: "canvas",
      mood: "calm",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereBars",
      label: "Atmosphere Bars",
      factory: atmosphereBarsFactory,
      visualType: "canvas",
      mood: "dynamic",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereRadial",
      label: "Atmosphere Multi-Shape",
      factory: atmosphereRadialFactory,
      visualType: "canvas",
      mood: "dynamic",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereColorWash",
      label: "Atmosphere Color Wash",
      factory: atmosphereColorWashFactory,
      visualType: "canvas",
      mood: "calm",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereKaleidoscope",
      label: "Atmosphere Kaleidoscope",
      factory: atmosphereKaleidoscopeFactory,
      visualType: "canvas",
      mood: "dynamic",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereSonar",
      label: "Atmosphere Sonar",
      factory: atmosphereSonarFactory,
      visualType: "canvas",
      mood: "dynamic",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereGlitch",
      label: "Atmosphere Glitch",
      factory: atmosphereGlitchFactory,
      visualType: "canvas",
      mood: "chaos",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereShatter",
      label: "Atmosphere Shatter",
      factory: atmosphereShatterFactory,
      visualType: "canvas",
      mood: "chaos",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereLaserGrid",
      label: "Atmosphere Laser Grid",
      factory: atmosphereLaserGridFactory,
      visualType: "canvas",
      mood: "dynamic",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereGlyphRain",
      label: "Atmosphere Glyph Rain",
      factory: atmosphereGlyphRainFactory,
      visualType: "canvas",
      mood: "calm",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereFirefly",
      label: "Atmosphere Firefly",
      factory: atmosphereFireflyFactory,
      visualType: "canvas",
      mood: "calm",
      role: "overlay",
      weight: 0,
    },
    {
      id: "atmosphereWarpStarfield",
      label: "Atmosphere Warp Starfield",
      factory: atmosphereWarpStarfieldFactory,
      visualType: "canvas",
      mood: "dynamic",
      role: "overlay",
      weight: 0,
    },
  ],
  presets: [],
};
