-- AlterTable
ALTER TABLE `homepagefeature` MODIFY `section` ENUM('SPOTLIGHT', 'FEATURED_ARTIST', 'FEATURED_PLAYLIST', 'CUSTOM_MIX', 'NEW_RELEASE', 'NEW_ARTIST', 'TRENDING', 'EDITOR_PICK', 'SITE_NEWS') NOT NULL;
